# Generated by Django 5.2.5 on 2025-09-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice',
            new_name='invoice_no',
        ),
    ]
