# Generated by Django 5.2.5 on 2025-09-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_rename_invoice_invoice_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
